import React, { useState, useMemo, useEffect } from 'react';
import { 
  X, 
  FileText, 
  CheckCircle, 
  AlertCircle, 
  Upload, 
  HelpCircle, 
  DollarSign, 
  Building, 
  Calendar, 
  Info,
  Paperclip,
  Check,
  ShieldCheck,
  UserCheck,
  RefreshCw,
  Lock,
  Sparkles
} from 'lucide-react';
import { 
  ArticleType, 
  AuthorRole, 
  DatabaseName, 
  DocumentAttachment, 
  JournalScope, 
  QuartileRank, 
  RequestType, 
  ResearchApplication,
  UserProfile 
} from '../types';
import { 
  calculateFacultyReward, 
  formatBaht, 
  formatThaiCitizenId, 
  formatKrungsriAccountNo, 
  formatPageChargeInput, 
  parsePageCharge,
  getTrackingPrefix,
  generateNextTrackingNo
} from '../data/regulations';
import { OFFICIAL_WORKFLOW_STEPS_DEF } from '../data/initialData';
import { getStoredUserProfile, saveStoredUserProfile } from '../data/userProfile';

interface SubmissionFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (newApp: Partial<ResearchApplication>) => void;
  existingApplications?: ResearchApplication[];
  currentUser?: UserProfile;
}

const DEPARTMENTS = [
  'ภาควิชาศัลยศาสตร์',
  'ภาควิชาอายุรศาสตร์',
  'ภาควิชากุมารเวชศาสตร์',
  'ภาควิชาสูติศาสตร์-นรีเวชวิทยา',
  'ภาควิชาออร์โธปิดิกส์',
  'ภาควิชาพยาธิวิทยา',
  'ภาควิชารังสีวิทยา',
  'ภาควิชาวิสัญญีวิทยา',
  'ภาควิชาจักษุวิทยา',
  'ภาควิชาโสต ศอ นาสิกวิทยา',
  'ภาควิชาจิตเวชศาสตร์',
  'ภาควิชาเวชศาสตร์ชุมชน',
  'ภาควิชาเวชศาสตร์ครอบครัว',
  'ภาควิชากายวิภาคศาสตร์',
  'ภาควิชาสรีรวิทยา',
  'ภาควิชาชีวเคมี',
  'ภาควิชาเภสัชวิทยา',
  'ภาควิชาจุลชีววิทยาและปรสิตวิทยา'
];

export const SubmissionFormModal: React.FC<SubmissionFormModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  existingApplications,
  currentUser,
}) => {
  // Active user profile (loaded from authentication / stored local profile)
  const activeUserProfile = useMemo(() => {
    return currentUser || getStoredUserProfile();
  }, [currentUser]);

  // Fiscal Year & Tracking Number states (Default to 2570 / AWP70-XXX)
  const [fiscalYear, setFiscalYear] = useState<number>(2570);
  const currentTrackingPrefix = useMemo(() => getTrackingPrefix(fiscalYear), [fiscalYear]);

  // Generate sequence tracking number based on fiscal year and existing applications
  const autoGeneratedTrackingNo = useMemo(() => {
    const existingTrackingNos = (existingApplications || []).map((a) => a.trackingNo);
    return generateNextTrackingNo(fiscalYear, existingTrackingNos);
  }, [fiscalYear, existingApplications]);

  const [trackingNoInput, setTrackingNoInput] = useState<string>(autoGeneratedTrackingNo);

  // When autoGeneratedTrackingNo changes, update input
  useEffect(() => {
    setTrackingNoInput(autoGeneratedTrackingNo);
  }, [autoGeneratedTrackingNo]);

  // Form states - Initialized with logged-in user profile (PDPA compliant, no hardcoded real researcher data)
  const [applicantName, setApplicantName] = useState<string>(activeUserProfile.name);
  const [academicPosition, setAcademicPosition] = useState<string>(activeUserProfile.academicPosition);
  const [department, setDepartment] = useState<string>(activeUserProfile.department);
  const [phone, setPhone] = useState<string>(activeUserProfile.phone);
  const [email, setEmail] = useState<string>(activeUserProfile.email);
  const [bankAccountNo, setBankAccountNo] = useState<string>(activeUserProfile.bankAccountNo || '');
  const [idCardNo, setIdCardNo] = useState<string>(activeUserProfile.idCardNo || '');

  // PDPA & Profile preference states
  const [pdpaConsentAccepted, setPdpaConsentAccepted] = useState<boolean>(true);
  const [rememberProfile, setRememberProfile] = useState<boolean>(true);
  const [profileReloadedNotice, setProfileReloadedNotice] = useState<boolean>(false);

  // Reload data from active profile
  const handleReloadFromUserProfile = () => {
    const freshProfile = currentUser || getStoredUserProfile();
    setApplicantName(freshProfile.name);
    setAcademicPosition(freshProfile.academicPosition);
    setDepartment(freshProfile.department);
    setPhone(freshProfile.phone);
    setEmail(freshProfile.email);
    setBankAccountNo(freshProfile.bankAccountNo || '');
    setIdCardNo(freshProfile.idCardNo || '');
    setProfileReloadedNotice(true);
    setTimeout(() => setProfileReloadedNotice(false), 3000);
  };

  const [requestType, setRequestType] = useState<RequestType>('both');
  const [articleTitle, setArticleTitle] = useState('');
  const [journalName, setJournalName] = useState('');
  const [journalScope, setJournalScope] = useState<JournalScope>('international');
  const [database, setDatabase] = useState<DatabaseName>('Web of Science');
  const [quartile, setQuartile] = useState<QuartileRank>('Q2');
  const [isTier1Top10, setIsTier1Top10] = useState(false);
  const [authorRole, setAuthorRole] = useState<AuthorRole>('first_author');
  const [articleType, setArticleType] = useState<ArticleType>('research_article');

  const [issn, setIssn] = useState('');
  const [doi, setDoi] = useState('');
  const [volumeIssue, setVolumeIssue] = useState('');
  const [publishedDate, setPublishedDate] = useState('2026-02-15');
  const [pageChargeInput, setPageChargeInput] = useState<string>('125,216.54');
  const [claimedPageCharge, setClaimedPageCharge] = useState<number>(125216.54);

  // Mandatory regulation compliance checkboxes
  const [medNuAffiliationDeclared, setMedNuAffiliationDeclared] = useState(true);
  const [notForGraduation, setNotForGraduation] = useState(true);
  const [within24Months, setWithin24Months] = useState(true);
  const [notPreviouslyClaimed, setNotPreviouslyClaimed] = useState(true);

  // Uploaded files simulation
  const [uploadedFiles, setUploadedFiles] = useState<{ [key: string]: boolean }>({
    reprint: true,
    quartileProof: true,
    invoice: true,
    idCard: true,
    bankBook: true,
  });

  // Dynamic calculation based on current inputs
  const calculation = useMemo(() => {
    return calculateFacultyReward({
      journalScope,
      database,
      quartile,
      isTier1Top10,
      authorRole,
      articleType,
      claimedPageCharge: requestType === 'reward_only' ? 0 : claimedPageCharge,
      alreadyUsedQuotaInYear: 0,
    });
  }, [journalScope, database, quartile, isTier1Top10, authorRole, articleType, claimedPageCharge, requestType]);

  // Handle Fiscal Year switch: automatically adapt prefix (e.g. AWP69 -> AWP70)
  const handleFiscalYearChange = (newYear: number) => {
    setFiscalYear(newYear);
    const oldPrefix = getTrackingPrefix(fiscalYear);
    const newPrefix = getTrackingPrefix(newYear);

    // If input begins with old prefix, swap it cleanly
    if (trackingNoInput.startsWith(oldPrefix)) {
      const suffix = trackingNoInput.substring(oldPrefix.length);
      setTrackingNoInput(`${newPrefix}${suffix}`);
    } else {
      const existingTrackingNos = (existingApplications || []).map((a) => a.trackingNo);
      setTrackingNoInput(generateNextTrackingNo(newYear, existingTrackingNos));
    }
  };

  const handleResetTrackingNo = () => {
    const existingTrackingNos = (existingApplications || []).map((a) => a.trackingNo);
    setTrackingNoInput(generateNextTrackingNo(fiscalYear, existingTrackingNos));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!pdpaConsentAccepted) {
      alert('กรุณาให้ความยินยอมตาม พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล (PDPA Consent) ก่อนส่งแบบคำขอ');
      return;
    }

    if (!articleTitle.trim() || !journalName.trim()) {
      alert('กรุณากรอกชื่อบทความวิจัย และชื่อวารสารให้ครบถ้วน');
      return;
    }

    if (!calculation.eligible) {
      alert(calculation.ineligibilityReason || 'ข้อมูลไม่ผ่านเกณฑ์การขอรับทุน');
      return;
    }

    // Save as default profile for next time if opted in
    if (rememberProfile) {
      saveStoredUserProfile({
        name: applicantName,
        academicPosition,
        department,
        phone,
        email,
        bankAccountNo,
        idCardNo,
      });
    }

    const generatedId = `app-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
    const finalTrackingNo = trackingNoInput.trim() || autoGeneratedTrackingNo;
    const today = new Date().toISOString().split('T')[0];

    const newApp: Partial<ResearchApplication> = {
      id: generatedId,
      trackingNo: finalTrackingNo,
      fiscalYear,
      createdAt: today,
      updatedAt: today,
      applicantName,
      academicPosition,
      department,
      phone,
      email,
      bankAccountNo,
      bankName: 'ธนาคารกรุงศรีอยุธยา สาขามหาวิทยาลัยนเรศวร',
      idCardNo,
      pdpaConsentAccepted: true,
      pdpaConsentDate: new Date().toISOString(),
      requestType,
      articleTitle,
      journalName,
      journalScope,
      database,
      quartile,
      isTier1Top10,
      authorRole,
      articleType,
      issn,
      doi,
      volumeIssue,
      publishedDate,
      within24Months,
      notForGraduation,
      medNuAffiliationDeclared,
      claimedRewardAmount: requestType === 'page_charge_only' ? 0 : calculation.rewardAmount,
      claimedPageChargeAmount: requestType === 'reward_only' ? 0 : claimedPageCharge,
      approvedPageChargeAmount: requestType === 'reward_only' ? 0 : calculation.approvedPageCharge,
      totalClaimedAmount: requestType === 'reward_only' 
        ? calculation.rewardAmount 
        : requestType === 'page_charge_only'
        ? calculation.approvedPageCharge
        : (calculation.rewardAmount + calculation.approvedPageCharge),
      currentStep: 1,
      status: 'submitted',
      paymentStatus: 'unpaid',
      attachments: [
        {
          id: 'att-user-1',
          title: 'สำเนา Reprint บทความวิจัย',
          type: 'reprint',
          fileName: `${journalName.substring(0, 15)}_reprint.pdf`,
          fileSize: '2.1 MB',
          uploadedAt: new Date().toISOString().split('T')[0],
          verified: false,
        },
        {
          id: 'att-user-2',
          title: 'เอกสารรับรอง Quartile จากฐานข้อมูล',
          type: 'quartile_proof',
          fileName: `${database}_proof.pdf`,
          fileSize: '750 KB',
          uploadedAt: new Date().toISOString().split('T')[0],
          verified: false,
        }
      ]
    };

    onSubmit(newApp);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-4 sm:p-6">
      <div className="bg-white rounded-2xl max-w-4xl w-full max-h-[92vh] flex flex-col shadow-2xl border border-slate-200 overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        
        {/* Modal Header */}
        <div className="bg-slate-900 px-6 py-4 flex items-center justify-between text-white border-b border-slate-800">
          <div>
            <div className="text-xs font-semibold text-amber-400 uppercase tracking-wider font-prompt flex items-center gap-2">
              <span>คณะแพทยศาสตร์ มหาวิทยาลัยนเรศวร</span>
              <span className="bg-amber-400/20 text-amber-300 px-2 py-0.5 rounded text-[10px] font-mono">
                {currentTrackingPrefix}
              </span>
            </div>
            <h2 className="text-lg font-bold text-white font-prompt flex items-center gap-2">
              <span>แบบคำขอรับเงินรางวัลและค่าตีพิมพ์บทความวิจัย ({currentTrackingPrefix})</span>
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Scrollable Body */}
        <form onSubmit={handleSubmit} className="overflow-y-auto p-6 space-y-6 text-xs text-slate-800">
          
          {/* Section 0: กำหนดปีงบประมาณและเลขที่ติดตาม (Dynamic Fiscal Year & AWP Prefix) */}
          <div className="bg-gradient-to-r from-blue-50/90 via-amber-50/40 to-slate-50 p-4 rounded-xl border border-blue-200/90 shadow-sm space-y-3">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 border-b border-blue-200/70 pb-2.5">
              <div className="font-bold text-slate-900 text-sm flex items-center gap-2 font-prompt">
                <span className="w-6 h-6 rounded-full bg-blue-700 text-white font-bold flex items-center justify-center text-xs shadow-sm">
                  ★
                </span>
                <span>ปีงบประมาณและเลขที่ติดตามคำขอ (Fiscal Year & Tracking No.)</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] text-slate-600 font-medium">รหัสนำหน้าตามปีงบ:</span>
                <span className="font-mono font-bold text-xs bg-blue-700 text-white px-2.5 py-0.5 rounded-md shadow-sm">
                  {currentTrackingPrefix}-XXX
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block font-medium text-slate-700 mb-1">
                  ปีงบประมาณ (พ.ศ.) *
                </label>
                <div className="flex items-center gap-2">
                  <select
                    value={fiscalYear}
                    onChange={(e) => handleFiscalYearChange(Number(e.target.value))}
                    className="flex-1 px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs font-semibold text-slate-900 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  >
                    <option value={2570}>ปีงบประมาณ 2570 (AWP70-XXX)</option>
                    <option value={2569}>ปีงบประมาณ 2569 (AWP69-XXX)</option>
                    <option value={2568}>ปีงบประมาณ 2568 (AWP68-XXX)</option>
                    <option value={2571}>ปีงบประมาณ 2571 (AWP71-XXX)</option>
                  </select>
                </div>
                <p className="text-[11px] text-slate-500 mt-1">
                  เมื่อเปลี่ยนปีงบประมาณ รหัสนำหน้าจะเปลี่ยนเป็น <strong className="text-blue-800">{currentTrackingPrefix}-</strong> ทันที
                </p>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1 flex items-center justify-between">
                  <span>เลขที่ติดตามคำขอ (Tracking No.) *</span>
                  <span className="text-[10px] text-blue-700 font-medium">ปรับเปลี่ยนได้ตามต้องการ</span>
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="text"
                    required
                    value={trackingNoInput}
                    onChange={(e) => setTrackingNoInput(e.target.value)}
                    placeholder={`เช่น ${currentTrackingPrefix}-001`}
                    className="flex-1 px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs font-mono font-bold text-blue-900 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  />
                  <button
                    type="button"
                    onClick={handleResetTrackingNo}
                    className="px-2.5 py-2 bg-slate-200 hover:bg-slate-300 text-slate-700 rounded-lg text-[11px] font-medium transition-colors shrink-0"
                    title="สร้างเลขลำดับถัดไปใหม่อัตโนมัติ"
                  >
                    รีเซ็ตลำดับ
                  </button>
                </div>
                <p className="text-[11px] text-slate-500 mt-1">
                  ตัวอย่าง: ปี 2569 ใช้ <strong>AWP69-XXX</strong> | ปี 2570 ใช้ <strong>AWP70-XXX</strong>
                </p>
              </div>
            </div>
          </div>

          {/* Section 1: ข้อมูลนักวิจัยผู้ขอรับทุน */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200/80 space-y-3">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-200 pb-2 gap-2">
              <div className="flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs font-bold">1</span>
                <span className="font-bold text-slate-900 text-sm font-prompt">
                  ข้อมูลผู้ขอรับทุนสนับสนุน (ส่วนของผู้รับทุน)
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="inline-flex items-center gap-1 text-[11px] px-2.5 py-0.5 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-300 font-medium">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" />
                  ดึงจากบัญชีผู้ล็อกอิน (PDPA Verified)
                </span>
                <button
                  type="button"
                  onClick={handleReloadFromUserProfile}
                  className="inline-flex items-center gap-1 text-[11px] text-blue-700 hover:text-blue-900 bg-white px-2 py-0.5 rounded border border-blue-200 hover:bg-blue-50 transition-colors"
                  title="รีโหลดข้อมูลจากบัญชีล็อกอินปัจจุบัน"
                >
                  <RefreshCw className="w-3 h-3" />
                  <span>ดึงข้อมูลอีกครั้ง</span>
                </button>
              </div>
            </div>

            {/* Notification if reloaded */}
            {profileReloadedNotice && (
              <div className="p-2 bg-emerald-50 border border-emerald-300 text-emerald-800 rounded-lg text-xs flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-emerald-600" />
                <span>ดึงข้อมูลตั้งต้นจากบัญชีล็อกอินเรียบร้อยแล้ว</span>
              </div>
            )}

            {/* SSO Info Bar */}
            <div className="p-2.5 bg-gradient-to-r from-blue-50 to-indigo-50/60 rounded-lg border border-blue-200 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
              <div className="flex items-center gap-2 text-slate-700">
                <UserCheck className="w-4 h-4 text-blue-600 shrink-0" />
                <span>
                  เชื่อมต่อข้อมูลผู้ใช้งาน: <strong className="text-blue-950 font-mono">{email}</strong>
                </span>
              </div>
              <label className="flex items-center gap-1.5 text-slate-600 cursor-pointer text-[11px]">
                <input
                  type="checkbox"
                  checked={rememberProfile}
                  onChange={(e) => setRememberProfile(e.target.checked)}
                  className="text-blue-600 rounded focus:ring-blue-500"
                />
                <span>บันทึกเป็นโปรไฟล์ตั้งต้นของฉัน</span>
              </label>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div>
                <label className="block font-medium text-slate-700 mb-1">ชื่อ - สกุล (พร้อมคำนำหน้า)*</label>
                <input
                  type="text"
                  required
                  value={applicantName}
                  onChange={(e) => setApplicantName(e.target.value)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none font-medium"
                />
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">ตำแหน่งทางวิชาการ</label>
                <input
                  type="text"
                  value={academicPosition}
                  onChange={(e) => setAcademicPosition(e.target.value)}
                  placeholder="เช่น ผู้ช่วยศาสตราจารย์"
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">ภาควิชาสังกัด*</label>
                <select
                  value={department}
                  onChange={(e) => setDepartment(e.target.value)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none font-medium"
                >
                  {DEPARTMENTS.map((dept) => (
                    <option key={dept} value={dept}>{dept}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">เบอร์โทรศัพท์ภายใน*</label>
                <input
                  type="text"
                  required
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  placeholder="เช่น 5588"
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">อีเมลมหาวิทยาลัย (@nu.ac.th)*</label>
                <input
                  type="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs font-mono text-slate-900 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
              </div>

              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="block font-medium text-slate-700">เลขประจำตัวประชาชน*</label>
                  <span className="text-[10px] text-slate-400 font-mono">จัดรูปแบบอัตโนมัติ</span>
                </div>
                <input
                  type="text"
                  required
                  maxLength={17}
                  inputMode="numeric"
                  placeholder="x-xxxx-xxxxx-xx-x"
                  value={idCardNo}
                  onChange={(e) => setIdCardNo(formatThaiCitizenId(e.target.value))}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs font-mono tracking-wider focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
              </div>

              <div className="sm:col-span-3 bg-blue-50/60 p-2.5 rounded-lg border border-blue-200 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-amber-500" />
                  <span className="font-semibold text-blue-900">
                    บัญชีรับโอนเงิน: ธนาคารกรุงศรีอยุธยา สาขามหาวิทยาลัยนเรศวร (ตามระเบียบคณะฯ)
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-slate-600 font-medium">เลขที่บัญชี:</span>
                  <input
                    type="text"
                    required
                    maxLength={13}
                    inputMode="numeric"
                    value={bankAccountNo}
                    onChange={(e) => setBankAccountNo(formatKrungsriAccountNo(e.target.value))}
                    placeholder="xxx-x-xxxxx-x"
                    className="px-2.5 py-1 bg-white border border-blue-300 rounded text-xs font-mono font-bold text-blue-950 tracking-wider focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Section 2: ข้อมูลการตีพิมพ์และการคำนวณ */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200/80 space-y-3">
            <div className="font-bold text-slate-900 text-sm flex items-center gap-2 border-b border-slate-200 pb-2 font-prompt">
              <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs">2</span>
              <span>ข้อมูลบทความวิชาการ และระดับวารสาร (คำนวณเงินอัตโนมัติ)</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="sm:col-span-3">
                <label className="block font-medium text-slate-700 mb-1">ประเภททุนที่ขอรับ*</label>
                <div className="flex flex-wrap gap-4 pt-1">
                  <label className="inline-flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="requestType"
                      checked={requestType === 'both'}
                      onChange={() => setRequestType('both')}
                      className="text-blue-600 focus:ring-blue-500"
                    />
                    <span className="font-semibold text-slate-800">ขอรับทั้งเงินรางวัลและค่าตีพิมพ์ (ทั้ง 2 รายการ)</span>
                  </label>
                  <label className="inline-flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="requestType"
                      checked={requestType === 'reward_only'}
                      onChange={() => setRequestType('reward_only')}
                      className="text-blue-600 focus:ring-blue-500"
                    />
                    <span>เฉพาะเงินรางวัลตีพิมพ์</span>
                  </label>
                  <label className="inline-flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="requestType"
                      checked={requestType === 'page_charge_only'}
                      onChange={() => setRequestType('page_charge_only')}
                      className="text-blue-600 focus:ring-blue-500"
                    />
                    <span>เฉพาะค่าตีพิมพ์ (Page Charge)</span>
                  </label>
                </div>
              </div>

              <div className="sm:col-span-2">
                <label className="block font-medium text-slate-700 mb-1">ชื่อบทความวิชาการ (Manuscript Title)*</label>
                <input
                  type="text"
                  required
                  value={articleTitle}
                  onChange={(e) => setArticleTitle(e.target.value)}
                  placeholder="เช่น Laparoscopic hepatectomy is feasible for patients diagnosed with..."
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">ชื่อวารสาร (Journal Name)*</label>
                <input
                  type="text"
                  required
                  value={journalName}
                  onChange={(e) => setJournalName(e.target.value)}
                  placeholder="เช่น World Journal of Gastrointestinal Surgery"
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">ระดับวารสาร*</label>
                <select
                  value={journalScope}
                  onChange={(e) => {
                    const scope = e.target.value as JournalScope;
                    setJournalScope(scope);
                    if (scope === 'national') {
                      setDatabase('TCI Tier 1');
                      setQuartile('TCI_1');
                    } else {
                      setDatabase('Web of Science');
                      setQuartile('Q1');
                    }
                  }}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                >
                  <option value="international">วารสารวิชาการระดับนานาชาติ (International)</option>
                  <option value="national">วารสารวิชาการระดับชาติ (National - TCI)</option>
                </select>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">ฐานข้อมูลอ้างอิง*</label>
                <select
                  value={database}
                  onChange={(e) => setDatabase(e.target.value as DatabaseName)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                >
                  {journalScope === 'international' ? (
                    <>
                      <option value="Web of Science">Web of Science</option>
                      <option value="Scopus">Scopus</option>
                      <option value="PubMed">PubMed</option>
                      <option value="SJR (SCImago)">SJR (SCImago Journal Rank)</option>
                    </>
                  ) : (
                    <>
                      <option value="TCI Tier 1">TCI กลุ่ม 1</option>
                      <option value="TCI Tier 2">TCI กลุ่ม 2</option>
                    </>
                  )}
                </select>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">Quartile / ระดับกลุ่ม*</label>
                <select
                  value={quartile}
                  onChange={(e) => setQuartile(e.target.value as QuartileRank)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none font-semibold text-blue-900"
                >
                  {journalScope === 'international' ? (
                    <>
                      <option value="Q1_Tier1">Quartile 1 (อยู่ในระดับ Tier 1 / Top 10%)</option>
                      <option value="Q1">Quartile 1 (Q1 ทั่วไป)</option>
                      <option value="Q2">Quartile 2 (Q2)</option>
                      <option value="Q3">Quartile 3 (Q3)</option>
                      <option value="Q4">Quartile 4 (Q4)</option>
                    </>
                  ) : (
                    <>
                      <option value="TCI_1">TCI กลุ่ม 1</option>
                      <option value="TCI_2">TCI กลุ่ม 2</option>
                    </>
                  )}
                </select>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">บทบาทการมีส่วนร่วมในผลงาน*</label>
                <select
                  value={authorRole}
                  onChange={(e) => setAuthorRole(e.target.value as AuthorRole)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                >
                  <option value="first_author">1) ผู้เขียนชื่อแรก (First Author)</option>
                  <option value="corresponding_author">2) ผู้เขียนชื่อหลัก (Corresponding Author)</option>
                  <option value="co_author">3) ผู้ร่วมเขียน (Co-author) - เฉพาะ Q1-Q2 (ได้ 50%)</option>
                </select>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">ประเภทของบทความ*</label>
                <select
                  value={articleType}
                  onChange={(e) => setArticleType(e.target.value as ArticleType)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                >
                  <option value="research_article">บทความวิจัย / บทความปริทัศน์ (Research / Review / Guidelines)</option>
                  <option value="other_academic">บทความวิชาการอื่นๆ (Case report, Clinical picture, Note)</option>
                </select>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">วันที่เผยแพร่ (Published Date)*</label>
                <input
                  type="date"
                  required
                  value={publishedDate}
                  onChange={(e) => setPublishedDate(e.target.value)}
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
              </div>

              {requestType !== 'reward_only' && (
                <div className="sm:col-span-3 bg-amber-50/70 p-3 rounded-lg border border-amber-200">
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                    <div>
                      <div className="flex items-center gap-2">
                        <label className="font-semibold text-amber-950 block">
                          ค่าตีพิมพ์จ่ายจริงตามใบเสร็จ (Page Charge / APC)*
                        </label>
                        <span className="text-[10px] bg-amber-200/80 text-amber-900 px-1.5 py-0.5 rounded font-mono font-bold">
                          รองรับจุดทศนิยม
                        </span>
                      </div>
                      <span className="text-[11px] text-amber-800">
                        กรอกยอดเงินบาทตามใบเสร็จหรือ Statement บัตรเครดิต เช่น 125,216.54 (ระบบใส่เครื่องหมายจุลภาคและคำนวณอัตโนมัติ)
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <input
                        type="text"
                        inputMode="decimal"
                        placeholder="เช่น 125,216.54"
                        value={pageChargeInput}
                        onChange={(e) => {
                          const formatted = formatPageChargeInput(e.target.value);
                          setPageChargeInput(formatted);
                          setClaimedPageCharge(parsePageCharge(formatted));
                        }}
                        onBlur={() => {
                          if (!pageChargeInput.trim()) {
                            setPageChargeInput('');
                            setClaimedPageCharge(0);
                            return;
                          }
                          const num = parsePageCharge(pageChargeInput);
                          if (pageChargeInput.includes('.') || num % 1 !== 0) {
                            setPageChargeInput(num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }));
                          } else {
                            setPageChargeInput(num.toLocaleString('en-US'));
                          }
                          setClaimedPageCharge(num);
                        }}
                        className="w-44 px-3 py-1.5 bg-white border border-amber-300 rounded text-xs font-bold text-amber-950 text-right focus:ring-2 focus:ring-amber-500 focus:outline-none font-mono"
                      />
                      <span className="font-semibold text-amber-900">บาท</span>
                    </div>
                  </div>

                  {claimedPageCharge > 0 && (
                    <div className="mt-2 pt-2 border-t border-amber-200/60 flex flex-wrap items-center justify-between text-[11px] text-amber-900">
                      <span>
                        ยอดจ่ายจริงตามใบเสร็จ: <strong className="font-mono font-bold text-amber-950">{formatBaht(claimedPageCharge)}</strong>
                      </span>
                      <span>
                        {claimedPageCharge > calculation.maxPageChargeAllowed ? (
                          <span className="text-amber-800 font-medium bg-amber-100/70 px-2 py-0.5 rounded">
                            (คณะฯ สนับสนุนตามประกาศฯ สูงสุดไม่เกิน <strong className="font-mono">{formatBaht(calculation.maxPageChargeAllowed)}</strong>)
                          </span>
                        ) : (
                          <span className="text-emerald-800 font-medium bg-emerald-100/70 px-2 py-0.5 rounded">
                            (ยอดอยู่ในเกณฑ์ สามารถเบิกจ่ายได้เต็มจำนวน <strong className="font-mono">{formatBaht(claimedPageCharge)}</strong>)
                          </span>
                        )}
                      </span>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Live Calculation Display Box */}
            <div className="bg-gradient-to-r from-blue-900 to-indigo-950 text-white p-4 rounded-xl shadow-md border border-blue-800 space-y-2">
              <div className="flex items-center justify-between">
                <span className="font-bold text-amber-400 font-prompt text-xs tracking-wider uppercase">
                  ผลการคำนวณตามเกณฑ์ประกาศ พ.ศ. 2567
                </span>
                <span className="text-[11px] bg-blue-800/80 px-2 py-0.5 rounded text-blue-200">
                  {calculation.ruleCitation}
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-2 border-t border-blue-800/80">
                <div>
                  <span className="text-blue-300 text-[11px] block">เงินรางวัลที่ได้สิทธิ:</span>
                  <span className="text-lg font-bold text-white font-prompt">
                    {formatBaht(requestType === 'page_charge_only' ? 0 : calculation.rewardAmount)}
                  </span>
                </div>

                <div>
                  <span className="text-blue-300 text-[11px] block">ค่าตีพิมพ์ที่อนุมัติ:</span>
                  <span className="text-lg font-bold text-white font-prompt">
                    {formatBaht(requestType === 'reward_only' ? 0 : calculation.approvedPageCharge)}
                  </span>
                </div>

                <div className="bg-amber-500/20 p-2 rounded-lg border border-amber-500/40">
                  <span className="text-amber-200 text-[11px] font-semibold block">ยอดเงินขออนุมัติสุทธิ:</span>
                  <span className="text-xl font-bold text-amber-300 font-prompt">
                    {formatBaht(
                      requestType === 'reward_only' 
                        ? calculation.rewardAmount 
                        : requestType === 'page_charge_only'
                        ? calculation.approvedPageCharge
                        : (calculation.rewardAmount + calculation.approvedPageCharge)
                    )}
                  </span>
                </div>
              </div>

              {calculation.notes.length > 0 && (
                <div className="pt-2 text-[11px] text-blue-200/90 space-y-0.5">
                  {calculation.notes.map((note, idx) => (
                    <div key={idx} className="flex items-center gap-1.5">
                      <Check className="w-3.5 h-3.5 text-amber-400 shrink-0" />
                      <span>{note}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Section 3: การรับรองคุณสมบัติตามระเบียบ (Mandatory Compliance) */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200/80 space-y-2.5">
            <div className="font-bold text-slate-900 text-sm flex items-center gap-2 border-b border-slate-200 pb-2 font-prompt">
              <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs">3</span>
              <span>การรับรองคุณสมบัติผู้ขอรับทุน (ตามประกาศมหาวิทยาลัยนเรศวร)</span>
            </div>

            <div className="space-y-2 text-slate-700">
              <label className="flex items-start gap-2.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={medNuAffiliationDeclared}
                  onChange={(e) => setMedNuAffiliationDeclared(e.target.checked)}
                  className="mt-0.5 text-blue-600 rounded focus:ring-blue-500"
                />
                <span>
                  ระบุชื่อตำแหน่งที่อยู่ผู้เขียนเป็น <strong>"Faculty of Medicine, Naresuan University"</strong> ในบทความวิชาการอย่างชัดเจน (ข้อ 5(2))
                </span>
              </label>

              <label className="flex items-start gap-2.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={notForGraduation}
                  onChange={(e) => setNotForGraduation(e.target.checked)}
                  className="mt-0.5 text-blue-600 rounded focus:ring-blue-500"
                />
                <span>
                  บทความวิชาการดังกล่าว <strong>ไม่ได้เป็นส่วนหนึ่งของการจบการศึกษาเพื่อปริญญา</strong> ของผู้ขอรับทุน (ข้อ 5(4))
                </span>
              </label>

              <label className="flex items-start gap-2.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={within24Months}
                  onChange={(e) => setWithin24Months(e.target.checked)}
                  className="mt-0.5 text-blue-600 rounded focus:ring-blue-500"
                />
                <span>
                  ผลงานได้รับการตีพิมพ์เผยแพร่มาแล้ว <strong>ไม่เกิน 24 เดือน</strong> นับตั้งแต่วันที่ตีพิมพ์จนถึงวันที่ยื่นเอกสาร (ข้อ 6(1))
                </span>
              </label>

              <label className="flex items-start gap-2.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={notPreviouslyClaimed}
                  onChange={(e) => setNotPreviouslyClaimed(e.target.checked)}
                  className="mt-0.5 text-blue-600 rounded focus:ring-blue-500"
                />
                <span>
                  <strong>ไม่เป็นบทความที่เคยขอรับการสนับสนุนค่าตีพิมพ์หรือรางวัลการตีพิมพ์มาก่อน</strong> (ข้อ 6(5))
                </span>
              </label>
            </div>
          </div>

          {/* Section 4: รายการเอกสารแนบ Checklist */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200/80 space-y-3">
            <div className="font-bold text-slate-900 text-sm flex items-center justify-between border-b border-slate-200 pb-2 font-prompt">
              <div className="flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs">4</span>
                <span>เอกสารประกอบการขอรับทุน ({currentTrackingPrefix} Checklist)</span>
              </div>
              <span className="text-[11px] text-slate-500 font-normal">แนบไฟล์ออนไลน์ & เตรียมสำหรับพิมพ์</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-slate-700">
              <div className="p-2.5 bg-white border border-slate-200 rounded-lg flex items-center justify-between">
                <span className="font-medium">1. สำเนาบทความ Reprint (ลงลายมือชื่อทุกหน้า)</span>
                <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 text-[10px] font-bold rounded">พร้อมแนบ</span>
              </div>

              <div className="p-2.5 bg-white border border-slate-200 rounded-lg flex items-center justify-between">
                <span className="font-medium">2. เอกสารรับรอง Quartile (SJR / WoS / Scopus / TCI)</span>
                <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 text-[10px] font-bold rounded">พร้อมแนบ</span>
              </div>

              <div className="p-2.5 bg-white border border-slate-200 rounded-lg flex items-center justify-between">
                <span className="font-medium">3. ใบแจ้งหนี้ (Invoice) หรือใบเสร็จรับเงินค่าตีพิมพ์</span>
                <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 text-[10px] font-bold rounded">พร้อมแนบ</span>
              </div>

              <div className="p-2.5 bg-white border border-slate-200 rounded-lg flex items-center justify-between">
                <span className="font-medium">4. สำเนาหน้าสมุดบัญชีธนาคารกรุงศรีอยุธยา</span>
                <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 text-[10px] font-bold rounded">พร้อมแนบ</span>
              </div>

              <div className="p-2.5 bg-white border border-slate-200 rounded-lg flex items-center justify-between sm:col-span-2">
                <span className="font-medium">5. สำเนาบัตรประจำตัวประชาชน (รับรองสำเนาถูกต้อง)</span>
                <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 text-[10px] font-bold rounded">พร้อมแนบ</span>
              </div>
            </div>
          </div>

          {/* Section 5: การให้ความยินยอมตาม พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล (PDPA Consent) */}
          <div className="bg-emerald-50/70 p-4 rounded-xl border border-emerald-200 space-y-2.5">
            <div className="font-bold text-emerald-950 text-sm flex items-center justify-between border-b border-emerald-200 pb-2 font-prompt">
              <div className="flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-emerald-700 text-white flex items-center justify-center text-xs font-bold">5</span>
                <span>การคุ้มครองข้อมูลส่วนบุคคล (PDPA Consent)</span>
              </div>
              <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 border border-emerald-300 font-semibold flex items-center gap-1">
                <ShieldCheck className="w-3 h-3 text-emerald-700" />
                พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562
              </span>
            </div>

            <p className="text-[11px] text-slate-700 leading-relaxed">
              ข้าพเจ้ายินยอมให้คณะแพทยศาสตร์ มหาวิทยาลัยนเรศวร เก็บรวบรวม ใช้ และประมวลผลข้อมูลส่วนบุคคลของข้าพเจ้า (รวมถึงชื่อ-นามสกุล, ข้อมูลสังกัด, เลขประจำตัวประชาชน, ข้อมูลบัญชีธนาคารกรุงศรีอยุธยา, อีเมล และเบอร์โทรศัพท์) เพื่อประโยชน์ในการตรวจสอบคุณสมบัตินักวิจัย อนุมัติเบิกจ่ายเงินรางวัล และการดำเนินการทางบัญชี/ภาษีอากรตามกฎหมายและระเบียบของมหาวิทยาลัยนเรศวร โดยข้อมูลจะได้รับการคุ้มครองความปลอดภัยตามมาตรการ PDPA ของมหาวิทยาลัย
            </p>

            <label className="flex items-start gap-2.5 cursor-pointer pt-1">
              <input
                type="checkbox"
                required
                checked={pdpaConsentAccepted}
                onChange={(e) => setPdpaConsentAccepted(e.target.checked)}
                className="mt-0.5 text-emerald-600 rounded focus:ring-emerald-500"
              />
              <span className="text-xs font-semibold text-emerald-900">
                ข้าพเจ้าได้อ่านและให้ความยินยอมในการประมวลผลข้อมูลส่วนบุคคลตามวัตถุประสงค์ข้างต้น (PDPA Consent)*
              </span>
            </label>
          </div>

          {/* Form Actions */}
          <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-slate-600 hover:text-slate-900 font-medium rounded-lg text-xs"
            >
              ยกเลิก
            </button>

            <button
              type="submit"
              className="px-6 py-2.5 bg-gradient-to-r from-blue-700 to-indigo-800 hover:from-blue-600 hover:to-indigo-700 text-white font-semibold rounded-lg text-xs shadow-md transition-all flex items-center gap-2"
            >
              <Upload className="w-4 h-4" />
              <span>บันทึกและส่งคำขอออนไลน์ (เข้าระบบงานวิจัย)</span>
            </button>
          </div>
        </form>

      </div>
    </div>
  );
};
